from entities.company import *
from entities.employee import *

empoyee_creation_query = f""" CREATE TABLE IF NOT EXISTS employee(
 {EMPLOYEE_ID} INTEGER PRIMARY KEY AUTO_INCREMENT , 
 {EMPLOYEE_photo} VARCHAR(100) , 
 {EMPLOYEE_BIO} VARCHAR(300) , 
 {EMPLOYEE_RESUME} VARCHAR(100) , 
 {EMPLOYEE_NAME} VARCHAR(100) NOT NULL , 
 {EMPLOYEE_PHONE} VARCHAR(20) NOT NULL , 
 {EMPLOYEE_EMAIL} VARCHAR(50) NOT NULL , 
 {EMPLOYEE_TITLE} VARCHAR(50) NOT NULL , 
 {EMPLOYEE_PASSWORD} VARCHAR(100) NOT NULL 
);
"""

company_creationQuery = f""" CREATE TABLE IF NOT EXISTS company(
 {COMPANY_ID} INTEGER PRIMARY KEY AUTO_INCREMENT , 
 {COMPANY_LOGO} VARCHAR(100) , 
 {COMPANY_NAME} VARCHAR(100) NOT NULL , 
 {COMPANY_INDUSTRY} VARCHAR(100) NOT NULL , 
 {COMPANY_WEBSITE} VARCHAR(100) , 
 {COMPANY_ABOUT} VARCHAR(300) , 
 {COMPANY_EMAIL} VARCHAR(100) NOT NULL , 
 {COMPANY_FACEBOOK_PAGE} VARCHAR(100) NOT NULL, 
 {COMPANY_PASSWORD} VARCHAR(100) NOT NULL 
);
"""

company_phone_creation_query = f""" CREATE TABLE IF NOT EXISTS company_phone(
 {COMPANY_ID_FK} INTEGER , 
 {COMPANY_PHONE} VARCHAR(20) NOT NULL , 
 FOREIGN KEY ({COMPANY_ID_FK}) REFERENCES company({COMPANY_ID}) ON DELETE CASCADE 
);
"""

company_address_creation_query = f""" CREATE TABLE IF NOT EXISTS company_address(
 {COMPANY_ID_FK} INTEGER , 
 {COMPANY_COUNTRY} VARCHAR(100) NOT NULL , 
 {COMPANY_CITY} VARCHAR(100) NOT NULL , 
 {COMPANY_STREET} VARCHAR(100) NOT NULL , 
 FOREIGN KEY ({COMPANY_ID_FK}) REFERENCES company({COMPANY_ID}) ON DELETE CASCADE 
);

"""
