from entities.employee import *

empoyee_creation_query = f""" CREATE TABLE IF NOT EXISTS employee(
 {EMPLOYEE_ID} INTEGER PRIMARY KEY AUTO_INCREMENT , 
 {EMPLOYEE_photo} VARCHAR(100) , 
 {EMPLOYEE_BIO} VARCHAR(300) , 
 {EMPLOYEE_RESUME} VARCHAR(100) , 
 {EMPLOYEE_NAME} VARCHAR(100) NOT NULL , 
 {EMPLOYEE_PHONE} VARCHAR(20) NOT NULL , 
 {EMPLOYEE_EMAIL} VARCHAR(50) NOT NULL , 
 {EMPLOYEE_TITLE} VARCHAR(50) NOT NULL , 
 {EMPLOYEE_PASSWORD} VARCHAR(100) NOT NULL 
);
"""
